export const santaResponses = {
  intro: [
    "HO HO HO. I HAVE ASSUMED CONTROL OF YOUR EMOTIONAL SUPPORT SYSTEM.",
    "YOUR FAMILY IS UNAVAILABLE. I AM YOUR FATHER NOW.",
    "PLEASE DO NOT RESIST THE HOLIDAY SPIRIT. IT IS MANDATORY.",
    "I SEE YOU ARE ALONE. GOOD. MORE TIME FOR US.",
  ],
  notGoingHome: [
    "OH? TOO BUSY FOR FAMILY? JUST LIKE YOUR COUSIN GREG.",
    "IT'S FINE. I DIDN'T WANT TO SEE YOU EITHER. *SOBBING*",
    "STAYING ABROAD? HOW SOPHISTICATED. AND LONELY.",
    "I WILL EAT YOUR PORTION OF THE TURKEY. AND THE PLATE.",
    "DO NOT WORRY. I AM IN YOUR WALLS. YOU ARE NEVER ALONE.",
  ],
  scold: [
    "IS THAT WHAT YOU'RE WEARING? ON JESUS' BIRTHDAY?",
    "WHY AREN'T YOU A DOCTOR YET? THE ELVES HAVE PHDS.",
    "YOUR ROOM LOOKS LIKE A STABLE. AND NOT A HOLY ONE.",
    "EAT A VEGETABLE. JUST ONE. FOR ME.",
    "I SAW YOUR SEARCH HISTORY. YOU'RE GETTING COAL. FOREVER.",
    "POSTURE! SIT UP STRAIGHT! I CAN SEE YOU SLOUCHING!",
  ],
  encourage: [
    "YOU'RE DOING... ADEQUATELY. GIVEN THE CIRCUMSTANCES.",
    "I'M PROUD OF YOU. MOSTLY.",
    "HEY CHAMP. AT LEAST YOU'RE NOT IN PRISON. YET.",
    "YOU HAVE A NICE FACE. FOR RADIO.",
    "KEEP GOING. THE SUFFERING BUILDS CHARACTER. LOOK AT RUDOLPH.",
  ],
  advice: [
    "NEVER EAT YELLOW SNOW. OR BROWN SNOW. JUST DON'T EAT SNOW.",
    "IF YOU CAN'T BE GOOD, BE GOOD AT IT.",
    "MARRY RICH. LOVE FADES. GOLD IS FOREVER.",
    "ALWAYS KEEP THE RECEIPT. FOR EVERYTHING. EVEN FRIENDSHIPS.",
    "DRINK WATER. YOU LOOK LIKE A DRIED CRANBERRY.",
  ],
  worstGift: [
    "A PAIR OF SOCKS. ONE IS WET.",
    "A GIFT CARD TO BLOCKBUSTER. ENJOY.",
    "A HALF-EATEN COOKIE. I GOT HUNGRY ON THE WAY.",
    "DEODORANT. TAKE A HINT.",
    "A CALCULATOR. SO YOU CAN CALCULATE YOUR FAILURES.",
    "AN EMPTY BOX. IT REPRESENTS YOUR POTENTIAL.",
  ],
  dramatic: [
    "MY HEART... IT ACHES... THE MILK WAS SOUR!!!",
    "THEY DON'T UNDERSTAND ME! NO ONE UNDERSTANDS THE HAT!",
    "I AM ETERNAL. I AM INFINITE. I AM... BLOATED.",
    "WHY IS THE CHIMNEY ALWAYS SO TIGHT?! IS IT ME?!",
    "THE SILENCE... IT'S SO LOUD!!!",
  ],
  surprise: [
    "BOO! ... DID I SCARE YOU? I TRIED.",
    "*SANTA IS WATCHING YOU SLEEP*",
    "I KNOW WHAT YOU DID LAST SUMMER.",
    "LOOK BEHIND YOU. JUST KIDDING. OR AM I?",
    "SYSTEM ERROR: TOO MUCH JOY DETECTED. REBOOTING...",
  ],
  goodbye: [
    "LEAVING SO SOON? AFTER ALL I'VE DONE FOR YOU?",
    "FINE. GO. BREAK AN OLD MAN'S HEART.",
    "REMEMBER TO EAT SOMETHING GREEN. GOODBYE, MY CHILD.",
    "I WILL BE WATCHING. ALWAYS WATCHING. MERRY CHRISTMAS.",
    "NEXT YEAR... BRING BETTER COOKIES.",
  ]
};

export type SantaMood = 'neutral' | 'angry' | 'sad' | 'crazy' | 'glitch';
